exclude_patterns = [
  "*.egg",
  "*.egg-info/**",
  ".eggs/**",
  ".git/**",
  ".tox/**",
  ".venv/**",
  "__pycache__/**",
  "bin/**",
  "build/**",
  "dist/**",
]
test_patterns = [
  "test_*.py",
  "tests/**",
]
version = 1

[[analyzers]]
enabled = true
name = "python"

[analyzers.meta]
runtime_version = "3.x"

[[transformers]]
enabled = true
name = "ruff"

[[transformers]]
enabled = true
name = "isort"
